### PR TITLE
Add forcePage prop

### PR DESCRIPTION
**Pull request by jbrodriguez**
For one of my projects I needed to replicate the forcePage prop of react-paginate.
This is the resulting code.
Let me know your comments.

### CODE REVIEW

**Comment by lokyoung** [comment]
Hello @jbrodriguez . Thanks for this PR. But set the default value of `forcePage` to 1 is not the correct behavior. It will lock to page 1. I will add a new PR and test case to handle this. Thanks!

**Comment by jbrodriguez** [comment]
Hi @lokyoung, sure, please close this PR as you see fit.

**Comment by lokyoung** [comment]
@jbrodriguez You can use latest version `0.8.0` to see if it solves your issue. Any feedback is welcome. Thanks!

**Comment by jbrodriguez** [comment]
Thanks @lokyoung, it looks great, I'll play with it in the next few days.

**Comment by jbrodriguez** [comment]
I was finally able to include it in my app, it works beautifully. Thanks !

**Comment by lokyoung** [comment]
@jbrodriguez . So glad to hear that. Also so much thanks for your feedback.

**Pull request closed without merging**
