### PR TITLE
improved algorithm in pages computed method

### PR DESCRIPTION
**Pull request by tomagnew**
The computed "pages" method uses a very expensive for loop in the function:

```
for (let index = 0; index < this.pageCount; index++) {
   ... // execute items logic
}
```
Using a pageCount of 100,000 pages slows the control down noticeably. At 1,000,000 pages the control has a 2 to 3 second lag time in the UI.

The code in this P/R executes the same logic only on three very small ranges including the low and high margin page ranges, plus the range around the selected page index. The result is excellent performance on even one trillion pages.

If interested, watch [https://youtu.be/RJoCskujh2s](https://youtu.be/RJoCskujh2s) for details on this fix.

### CODE REVIEW

**Comment by lokyoung** [comment]
Hi @tomagnew . I'm really appreciated of your work. I will take review at the code and publish a new version. Thanks.

**Comment by tomagnew** [comment]
Hi @lokyoung , you're very welcome. I like this component and am planning on using it in many projects. Thank you.

**Comment by lokyoung** [comment]
@tomagnew I just make some simple updates.
- Remove the indentation between `template` and `style` tag since there is a convention for vue. 
- Use camel case for the two variable `selectedRange_low` and `selectedRange_high`. In JavaScript, we often use camel case. BTW, i'm also a Ruby developer, in Ruby we use snake case so  i feel so kind to see that case lol.

So impressed for your work, Thanks!

**Comment by lokyoung** [comment]
@tomagnew I have published a new version `v1.1.0`. You can check if it's ok. And issue please feel free to contact me.

**Pull request merged**
